# settings to be used when running in local dev environment 

app:
  db:
    host: 192.168.99.100
    port: 13306
    database: todo-db
    user: todo-user
    password: todo-password

logging.level.com.merikan: debug

